# Generated by Django 4.0 on 2021-12-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorgImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('img', models.ImageField(upload_to='media/corgi/images')),
                ('created_on', models.TimeField(auto_now=True)),
            ],
        ),
    ]
