# Generated by Django 4.0 on 2022-09-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_counter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CorgImage',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='CorgImageUrls',
            new_name='Url',
        ),
    ]
